swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: Environment sensor
  description: API to read smarthome sensor
  contact:
    name: Jacob Sohl
    url: github.com/hmm01i
    email: hmm01i@gmail.com
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /sensors:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `sensor` objects.
        Optional query param of **size** determines
        size of returned array
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfSensors
            type: array
            items:
              title: Sensor
              type: object
              properties:
                id:
                  type: number
                name:
                  type: string
                unit:
                  type: string
                min:
                  type: number
                  format: float
                max:
                  type: number
                  format: float
  /sensor/{id}:
    get:
      description: |
        Gets `sensor` objects.
      # This is array of GET operation parameters:
      parameters:
        -
          name: id
          in: path
          description: id of sensor
          required: true
          type: number
          format: integer
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: Sensor
            type: object
            properties:
              id:
                type: number
              name:
                type: string
              unit:
                type: string
              min:
                type: number
              max:
                type: number
              value:
                type: number
  /health:
    get:
      description: |
        Get health of device.
      responses:
        200:
          description: Successfuly response
          schema:
            title: status
            type: object
            properties:
              name:
                type: string
              id:
                type: number
              location:
                type: string
              firmware:
                type: string
              fw version:
                type: string
              uptime:
                type: string
        400:
          description: Something is wrong
          schema:
            title: status
            type: string
